# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: DevBuild

concurrency:
  group: "${{ github.workflow }}/${{ github.ref }}"
  cancel-in-progress: false

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    # config strategy
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        version: [ 8.0 ]
        # temp: disable macos test
        # os: [ ubuntu-latest, windows-latest ]
        # temp: disable macos and linux test
        # os: [ windows-latest ]
        # note: test all os
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    # config os
    runs-on: ${{ matrix.os }}
    # config steps
    steps:
      # config environment
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        # config dotnet version
        with:
          dotnet-version: ${{ matrix.version }}
      # restore dependencies
      - name: Restore Netly Project
        run: dotnet restore ./src/Netly.csproj
      # run netly test
      - name: Build Netly Library
        run: dotnet build ./src/Netly.csproj -c Debug --no-restore
